import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { RootProvider } from "fumadocs-ui/provider";
import type { ReactNode } from "react";
import { cn } from "@foundations/shadcn/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          crossOrigin="anonymous"
          src="//cdn.jsdelivr.net/npm/meta-scan@0.10.0/dist/auto.global.js"
          data-auto-enable={
            process.env.NODE_ENV === "development" ? "true" : "false"
          }
        />
      </head>
      <body
        className={cn(
          "bg-background overscroll-none font-sans antialiased",
          `${geistSans.variable} ${geistMono.variable}`
        )}
      >
        {children}
      </body>
    </html>
  );
}
